### ISSUE TITLE
Improve date display in banlist

### ISSUE THREAD

**Issue by freddyheppell** [andyksaw/ProjectCityBuild#173]
Should really display the date instead of human diff

**Comment by andyksaw** [comment]
Or maybe 'today', 'yesterday' and the rest as a date

**Comment by freddyheppell** [comment]
This kind of display better?
<img width="299" alt="Screenshot 2019-08-10 at 16 26 12" src="https://user-images.githubusercontent.com/1475568/62823691-a7b4c100-bb8b-11e9-8d31-e4ad0e3e58ac.png">

**Comment by freddyheppell** [comment]
Fixed in #187
