### ISSUE TITLE
Issue with SCSS building times

### ISSUE THREAD

**Issue by freddyheppell** [andyksaw/ProjectCityBuild#198]
There's something taking a very long time to build SCSS, takes about 10s on my machine. This is much much longer than a project importing bootstrap so clearly something's wrong here. 

@andyksaw can you try building CSS on `dev` at the moment and see if it takes unreasonably long for you too?

**Comment by andyksaw** [comment]
It's taking an unusually long time for me too 🤔

**Comment by freddyheppell** [comment]
I've been able to figure out it's this line:
https://github.com/andyksaw/ProjectCityBuild/blob/dev/src/resources/sass/app.scss#L60

**Comment by freddyheppell** [comment]
Fixed by disabling `processCssUrls` even though it wouldn't use it for that line as it's an absolute path
