### ISSUE TITLE
Deal with social login

### ISSUE THREAD

**Issue by freddyheppell** [andyksaw/ProjectCityBuild#65]
Social login is definitely the most fragile part of the site and the vast majority of errors we get seem to be caused by it. If someone uses social login then they also can't use `/login` in-game.

I propose removing social login from the site entirely and just using password auth. We'd need to check if anyone has actually succesfully used it, and if so make sure they can use password auth by resetting their password.

**Comment by andyksaw** [comment]
It's a shame because there's quite a number of people using/trying to use social login, but it's definitely causing more problems than solving.

I'll remove it in the next update

**Comment by freddyheppell** [comment]
It's probably just because it's an option, if it's not there people probably won't miss it.

**Comment by andyksaw** [comment]
Handled in the above PR
